server:
  port: 9876
  
spring:
  application:
    name: IAM API server
  
  jpa:
    open-in-view: false
    generate-ddl: false
    
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   
  jackson:
    default-property-inclusion: non-null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    property-naming-strategy: LOWER_CAMEL_CASE
  flyway:
    enabled: false

iam:
  oauth-keys-refresh-period-minutes: 60