spring:
  application:
    name: IAM API server
  
  jpa:
    open-in-view: false
    generate-ddl: false
    
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   
  jackson:
    default-property-inclusion: non-null
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    
  h2:
    console:
      enabled: false
  
  flyway:
    locations:
    - classpath:/db/migration/iam

iam:
  oauth-keys-refresh-period-minutes: 60