spring:
  datasource:
    url: jdbc:tc:mysql:5.7:///iam?TC_DAEMON=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop