spring:
  profiles:
    include: h2-console,test
    
  datasource:
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations:
    - classpath:/db/migration/iam
    - classpath:/db/migration/test 
  
  h2:
    console:
      enabled: true