spring:
  profiles:
    include: test
    
  datasource:
    url: jdbc:tc:mysql:5.7:///iam
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      
  flyway:
    enabled: true
    locations:
    - classpath:/db/migration/iam
    - classpath:/db/migration/test 