create table EMAIL_NOTIFICATIONS (ID bigint not null auto_increment, BODY longtext not null, CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, STATUS varchar(255) not null, SUBJECT varchar(128) not null, TYPE varchar(32) not null, UUID varchar(36) not null, REALM_ID bigint not null, primary key (ID)) engine=InnoDB;
create table EMAIL_NOTIFICATIONS_RECIPIENTS (NOTIFICATION_ID bigint not null, RECIPIENT_ADDR varchar(255)) engine=InnoDB;
create table REALMS (ID bigint not null auto_increment, AUP_URL varchar(128), CONFIG longtext not null, DESCRIPTION varchar(512), LOGO_URL varchar(128), CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, NAME varchar(255), PRIVACY_POLICY_URL varchar(128), REGISTRATION_ENABLED bit not null, primary key (ID)) engine=InnoDB;
create table REG_REQUESTS (ID bigint not null auto_increment, EMAIL_CHALLENGE varchar(36) not null, CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, OUTCOME varchar(16), CHALLENGE varchar(36) not null, EMAIL varchar(128) not null, EMAIL_VERIFIED bit not null, FAMILY_NAME varchar(128) not null, GIVEN_NAME varchar(128) not null, USERNAME varchar(128) not null, STATUS varchar(50) not null, uuid varchar(36) not null, REALM_ID bigint not null, primary key (ID)) engine=InnoDB;
create table REG_REQUESTS_ATTACHMENTS (ID bigint not null auto_increment, CONTENT longtext not null, LABEL varchar(36) not null, CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, REG_REQ_ID bigint not null, primary key (ID)) engine=InnoDB;
create table REG_REQUESTS_LABELS (REQ_ID bigint not null, L_NAME varchar(64) not null, L_PREFIX varchar(256), L_VAL varchar(64)) engine=InnoDB;
create table REG_REQUESTS_MESSAGES (REQ_ID bigint not null, CREATION_TIME datetime(6) not null, MESSAGE varchar(512) not null, SENDER varchar(255)) engine=InnoDB;
create table REG_REQUESTS_OTHERINFO (RegistrationRequestEntity_ID bigint not null, OI_VAL varchar(255), OI_KEY varchar(255) not null, primary key (RegistrationRequestEntity_ID, OI_KEY)) engine=InnoDB;
alter table EMAIL_NOTIFICATIONS add constraint UK_5pmpaw6ctts5a9rthgauo7ke3 unique (UUID);
create index IDX26txk3towmw5ygpuj4dm7i3ff on EMAIL_NOTIFICATIONS_RECIPIENTS (RECIPIENT_ADDR);
alter table EMAIL_NOTIFICATIONS_RECIPIENTS add constraint UKp8pqf786bw49sa0ce5dgwqjh unique (NOTIFICATION_ID, RECIPIENT_ADDR);
alter table REALMS add constraint UK_kixct1r0c522ddn7w0fp4utih unique (NAME);
alter table REG_REQUESTS add constraint UK5tbld2lnkjpv2vex2j1u7nkvx unique (REALM_ID, CHALLENGE);
alter table REG_REQUESTS add constraint UK52ehwln4qj7pa1g60lqf2gafg unique (REALM_ID, EMAIL_CHALLENGE);
alter table REG_REQUESTS add constraint UK_47gob5kicryg0ejy3uh5rsy1b unique (CHALLENGE);
alter table REG_REQUESTS add constraint UK_pggp2s4x6qliak45gc7xant1 unique (uuid);
create index IDXgadcub52wuydckht0p7ppkusx on REG_REQUESTS_LABELS (L_PREFIX, L_NAME, L_VAL);
create index IDX1lorot8kvvss7otjoxs5it8py on REG_REQUESTS_LABELS (L_PREFIX, L_NAME);
alter table EMAIL_NOTIFICATIONS add constraint FK2mcyrxv98ux21s8ie9wxj0s2k foreign key (REALM_ID) references REALMS (ID);
alter table EMAIL_NOTIFICATIONS_RECIPIENTS add constraint FKf2fvamhcbybdfkj5572022ll3 foreign key (NOTIFICATION_ID) references EMAIL_NOTIFICATIONS (ID);
alter table REG_REQUESTS add constraint FK4hn9movuw1xux4n47oxnowdlo foreign key (REALM_ID) references REALMS (ID);
alter table REG_REQUESTS_ATTACHMENTS add constraint FK94burs7fwk4bxd815qn8l2ogo foreign key (REG_REQ_ID) references REG_REQUESTS (ID);
alter table REG_REQUESTS_LABELS add constraint FKenf2l9m53iqaovgeg0tncq12b foreign key (REQ_ID) references REG_REQUESTS (ID);
alter table REG_REQUESTS_MESSAGES add constraint FKdtom5c7axvrj5o75getmtwk1b foreign key (REQ_ID) references REG_REQUESTS (ID);
alter table REG_REQUESTS_OTHERINFO add constraint FKe93mpb27tttdsxkaxxsogmmal foreign key (RegistrationRequestEntity_ID) references REG_REQUESTS (ID);
