version: "3.5"

volumes:
  data:

services:

  db:
    image: ${DB_IMAGE}
    volumes:
      - data:/var/lib/mysql
    
    environment:
      TZ: Europe/Rome

    ports:
      - "3306:3306"

  kc:
    image: ${KEYCLOAK_IMAGE} 
    environment:
      TZ: Europe/Rome
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: kc
      DB_USER: kc
      DB_PASSWORD: pwd
      JDBC_PARAMS: useSSL=false

      # volumes:
      # - ./assets/keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      # - ./../iam-kc-user-storage-provider/target/iam-kc-user-storage-provider-2.0.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/iam-provider.jar
      # - ./../iam-entities/target/iam-entities-2.0.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/iam-entities.jar

    depends_on:
      - db
    ports:
      - "8080:8080"
