#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2020
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3.5"

volumes:
  data:

services:
  db:
    image: ${DB_IMAGE}
    # volumes:
    # - data:/var/lib/mysql

    environment:
      TZ: Europe/Rome

    ports:
      - "3306:3306"

  kc:
    image: ${KEYCLOAK_IMAGE}
    environment:
      TZ: Europe/Rome
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_DATABASE: kc
      DB_USER: kc
      DB_PASSWORD: pwd
      JDBC_PARAMS: useSSL=false

    command: -b 0.0.0.0 --debug 0.0.0.0:8787

    volumes:
      - ./assets/keycloak/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml:rw
      - ./../iam-kc-user-storage-provider-ear/target/iam-kc-user-storage-provider-ear-2.0.0-SNAPSHOT.ear:/opt/jboss/keycloak/standalone/deployments/iam-provider.ear

    depends_on:
      - db

    ports:
      - "8080:8080"
      - "8787:8787"
