insert into REALMS(ID,NAME,DESCRIPTION,CONFIG,CREATION_TIME,LAST_UPDATE_TIME) 
    values (1,'iam', 'The iam realm', '{}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
 
insert into REALMS(ID,NAME,DESCRIPTION,CONFIG,CREATION_TIME,LAST_UPDATE_TIME) 
    values (2,'alice', 'The alice realm', '{}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
    
insert into REALMS(ID,NAME,DESCRIPTION,CONFIG,CREATION_TIME,LAST_UPDATE_TIME) 
    values (3,'atlas', 'The atlas realm', '{}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into REALMS(ID,NAME,DESCRIPTION,CONFIG,CREATION_TIME,LAST_UPDATE_TIME) 
    values (4,'cms', 'The cms realm', '{}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
 
insert into REALMS(ID,NAME,DESCRIPTION,CONFIG,CREATION_TIME,LAST_UPDATE_TIME) 
    values (5,'lhcb', 'The lhcb realm', '{}', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into GROUPS(ID,REALM_ID,NAME,UUID,PARENT_GROUP_ID,CREATION_TIME,LAST_UPDATE_TIME)
    values (100,2,'alice', UUID(), null,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into GROUPS(ID,REALM_ID,NAME,UUID,PARENT_GROUP_ID,CREATION_TIME,LAST_UPDATE_TIME)
    values (101,2,'alice/production', UUID(), 100,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
 