create table CONFIG (ID bigint not null auto_increment, CONFIG longtext not null, DESCRIPTION varchar(512), CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, NAME varchar(128) not null, primary key (ID)) ;
create table GROUPS (ID bigint not null auto_increment, DESCRIPTION varchar(512), CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, NAME varchar(512) not null, UUID varchar(36) not null, PARENT_GROUP_ID bigint, primary key (ID)) ;
create table GROUPS_ATTRIBUTES (GROUP_ID bigint not null, A_NAME varchar(64) not null, A_VAL varchar(256)) ;
create table GROUPS_LABELS (GROUP_ID bigint not null, L_NAME varchar(64) not null, L_PREFIX varchar(256), L_VAL varchar(64)) ;
create table ROLES (ID bigint not null auto_increment, DESCRIPTION varchar(512), CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, NAME varchar(512) not null, UUID varchar(36) not null, primary key (ID)) ;
create table ROLES_ATTRIBUTES (ROLE_ID bigint not null, A_NAME varchar(64) not null, A_VAL varchar(256)) ;
create table ROLES_LABELS (ROLE_ID bigint not null, L_NAME varchar(64) not null, L_PREFIX varchar(256), L_VAL varchar(64)) ;
create table USERS (ID bigint not null auto_increment, ACTIVE bit not null, CREATION_TIME datetime(6) not null, LAST_UPDATE_TIME datetime(6) not null, PASSWORD varchar(128), PROVISIONED bit not null, USERNAME varchar(128) not null, UUID varchar(36) not null, primary key (ID)) ;
create table USERS_ATTRIBUTES (USER_ID bigint not null, A_NAME varchar(64) not null, A_VAL varchar(256)) ;
create table USERS_EMAILS (USER_ID bigint not null, EMAIL varchar(128) not null, LABEL varchar(36), IS_PRIMARY bit not null, EMAIL_VERIFIED bit not null) ;
create table USERS_GROUPS (USER_ID bigint not null, GROUP_ID bigint not null, primary key (USER_ID, GROUP_ID)) ;
create table USERS_LABELS (USER_ID bigint not null, L_NAME varchar(64) not null, L_PREFIX varchar(256), L_VAL varchar(64)) ;
create table USERS_ROLES (USER_ID bigint not null, ROLE_ID bigint not null, primary key (USER_ID, ROLE_ID)) ;
alter table CONFIG add constraint UK_46nwu64m3fxavev9smr4jww92 unique (NAME);
alter table GROUPS add constraint UK_2p0nwsuci8u6jngkjbfueinox unique (NAME);
alter table GROUPS add constraint UK_nibi5aro3orcni4n3697umtdx unique (UUID);
create index IDX7x16wlobyvr4xapmm63hn6x9x on GROUPS_ATTRIBUTES (A_NAME);
create index IDXqe6tmrt2splq0dqskhq61acu on GROUPS_ATTRIBUTES (A_NAME, A_VAL);
create index IDX2chuoabqivj2xpjwrl1p5i6kk on GROUPS_LABELS (L_PREFIX, L_NAME, L_VAL);
create index IDXhw8rq8rmt97vb4wt7h6mf0n3t on GROUPS_LABELS (L_PREFIX, L_NAME);
alter table ROLES add constraint UK_lpdecwdy9vmiwufr3k4a2quus unique (NAME);
alter table ROLES add constraint UK_tj41cr26fvuhhul71j9alt378 unique (UUID);
create index IDX4rso2kb8er4e2ie56oxpscwey on ROLES_ATTRIBUTES (A_NAME);
create index IDXbkygd955erius73mewdlx3h9d on ROLES_ATTRIBUTES (A_NAME, A_VAL);
create index IDXel13hd129kf3q7ul04qi8an07 on ROLES_LABELS (L_PREFIX, L_NAME, L_VAL);
create index IDX5d3elfqwp3ulms5ox89xcpai3 on ROLES_LABELS (L_PREFIX, L_NAME);
alter table USERS add constraint UK_h6k33r31i2nvrri9lok4r163j unique (USERNAME);
alter table USERS add constraint UK_ovbs0bj90qkj1fq1654jjjcue unique (UUID);
create index IDXba6tpqyju18n0r3v81t2ics7b on USERS_ATTRIBUTES (A_NAME);
create index IDX79lpagn5lamucoaj3g17gqnlv on USERS_ATTRIBUTES (A_NAME, A_VAL);
create index IDX9sersqdt56vsp1wskktbrtupm on USERS_EMAILS (EMAIL);
create index IDXcq3fjnym8g5hrq2lg5w6bmcpk on USERS_EMAILS (LABEL);
create index IDX3yyakh9ra4no2ic469mmdev9h on USERS_LABELS (L_PREFIX, L_NAME, L_VAL);
create index IDX5jal76ntebkr03bwbbahacl6n on USERS_LABELS (L_PREFIX, L_NAME);
alter table GROUPS add constraint FKlrpdyeywdl5bm4cm3oi794ypl foreign key (PARENT_GROUP_ID) references GROUPS (ID);
alter table GROUPS_ATTRIBUTES add constraint FKsc6vkubpe21ia6d3pk86yvvyt foreign key (GROUP_ID) references GROUPS (ID);
alter table GROUPS_LABELS add constraint FK54qhf7g499h97fjjvy9pobqda foreign key (GROUP_ID) references GROUPS (ID);
alter table ROLES_ATTRIBUTES add constraint FKnh5bbslmec04iba7mj7i2srb3 foreign key (ROLE_ID) references ROLES (ID);
alter table ROLES_LABELS add constraint FKkn3tk8237penmm0im6g0017ca foreign key (ROLE_ID) references ROLES (ID);
alter table USERS_ATTRIBUTES add constraint FKd388ixgf1eaq3jpss5yp84ejx foreign key (USER_ID) references USERS (ID);
alter table USERS_EMAILS add constraint FKpybnm4bidnf86olskjc9iqmks foreign key (USER_ID) references USERS (ID);
alter table USERS_GROUPS add constraint FK3yi73qgrwhbuhvjydbvevyqj5 foreign key (GROUP_ID) references GROUPS (ID);
alter table USERS_GROUPS add constraint FK9wgkqynxvx2vk1mdx52fp175s foreign key (USER_ID) references USERS (ID);
alter table USERS_LABELS add constraint FK9mlpbwtgr3mmlgreh2fvum9l8 foreign key (USER_ID) references USERS (ID);
alter table USERS_ROLES add constraint FKoaraxqcxi9fou9oqpjrc4nx68 foreign key (ROLE_ID) references ROLES (ID);
alter table USERS_ROLES add constraint FK12v220v0594jj67ajy0u6xdvu foreign key (USER_ID) references USERS (ID);